param(
    [switch]$prod
)

$SECRETS=aws secretsmanager get-secret-value --secret-id "REDDIT-CCAutoFlair" --region us-east-2 --query SecretString --output json | convertfrom-json | convertfrom-json -AsHashtable 

$ENV:REDDIT_SCRIPT_ID = $SECRETS.REDDIT_SCRIPT_ID_PRODUCTION
$ENV:REDDIT_SCRIPT_SECRET = $SECRETS.REDDIT_SCRIPT_SECRET_PRODUCTION
$ENV:REDDITUSER = $SECRETS.REDDIT_USER
$ENV:REDDITUSERPASSWORD = $SECRETS.REDDIT_PASSWORD_PRODUCTION
$ENV:MYSQL_USER = $SECRETS.MYSQL_USER 
$ENV:MYSQL_PASSWORD = $SECRETS.MYSQL_PASSWORD
$ENV:MYSQL_SERVER = $SECRETS.MYSQL_SERVER
$ENV:MYSQL_SERVER_PORT = $SECRETS.MYSQL_SERVER_PORT

. ./functions.ps1